### ISSUE TITLE
文章标题目录

### ISSUE THREAD

**Issue by ghost** [zjhch123/solo-skin-emiya#1]
能不能添加个文章内标题索引目录呢，长博文没有这个有点难受。

**Comment by AlgerFan** [comment]
自己加了个，但是不太好用

**Comment by zjhch123** [comment]
我也有过相关的思考，但是似乎没有找到一个合适的位置放目录。请问你们有什么建议吗？

**Comment by AlgerFan** [comment]
> 我也有过相关的思考，但是似乎没有找到一个合适的位置放目录。请问你们有什么建议吗？

我试过放在右边侧边栏，下滑一定高度后，固定在右边，由于我主Java开发，前端太菜，一定高度后固定，处理不好

**Comment by zjhch123** [comment]
> > 我也有过相关的思考，但是似乎没有找到一个合适的位置放目录。请问你们有什么建议吗？
> 
> 我试过放在右边侧边栏，下滑一定高度后，固定在右边，由于我主Java开发，前端太菜，一定高度后固定，处理不好

好的，多谢建议。我会尝试处理~

**Comment by zjhch123** [comment]
已增加，可以更新到最新版本查看效果 ~

**Comment by AlgerFan** [comment]
> 已增加，可以更新到最新版本查看效果 ~

收到😏
