### ISSUE TITLE
目录问题

### ISSUE THREAD

**Issue by AlgerFan** [zjhch123/solo-skin-emiya#12]
页面拉到最底部，目录和底部重叠
![TIM图片20191102205516.png](https://img.algerfan.cn/blog/image/20191102/513082e1f9574648ad876a6cda76a64a.png)

**Comment by zjhch123** [comment]
好的！收到！

**Comment by zjhch123** [comment]
已修复 ~  感谢！

**Comment by AlgerFan** [comment]
> 已修复 ~ 感谢！

好的😊

**Comment by AlgerFan** [comment]
效果真棒👍，感谢大佬👏👏

**Comment by zjhch123** [comment]
> 效果真棒👍，感谢大佬👏👏

你的博客里有一些文章的目录标题很长，换行之后样式有点难看，我又优化了一下。你可以pull一下现在最新的master分支看看效果（或者直接覆盖css文件也可以哈

**Comment by AlgerFan** [comment]
> > 效果真棒+1，感谢大佬clapclap
> 
> 你的博客里有一些文章的目录标题很长，换行之后样式有点难看，我又优化了一下。你可以pull一下现在最新的master分支看看效果（或者直接覆盖css文件也可以哈

好的好的，这么晚了，是在加班吗？

**Comment by zjhch123** [comment]
> > > 效果真棒+1，感谢大佬clapclap
> > 
> > 
> > 你的博客里有一些文章的目录标题很长，换行之后样式有点难看，我又优化了一下。你可以pull一下现在最新的master分支看看效果（或者直接覆盖css文件也可以哈
> 
> 好的好的，这么晚了，是在加班吗？

没有啊哈哈，在等0点的动漫更新😀

**Comment by AlgerFan** [comment]
> > > > 效果真棒+1，感谢大佬clapclap
> > > 
> > > 
> > > 你的博客里有一些文章的目录标题很长，换行之后样式有点难看，我又优化了一下。你可以pull一下现在最新的master分支看看效果（或者直接覆盖css文件也可以哈
> > 
> > 
> > 好的好的，这么晚了，是在加班吗？
> 
> 没有啊哈哈，在等0点的动漫更新

可以可以
