### ISSUE TITLE
申请移植皮肤

### ISSUE THREAD

**Issue by adlered** [zjhch123/solo-skin-emiya#15]
zjhch123 你好 :smile: ，[bolo-solo](https://github.com/AdlerED/bolo-solo) 是基于 Solo 的一款离线化博客系统，觉得 emiya 这个主题非常好看，不知道可否授权我移植到 bolo-solo 当中，作为预置皮肤？多谢~

**Comment by zjhch123** [comment]
当然可以，辛苦！
