### ISSUE TITLE
文章目录过长时，无法显示后边的部分

### ISSUE THREAD

**Issue by AlgerFan** [zjhch123/solo-skin-emiya#16]
文章目录过长时，无法显示后边的部分，只有拉到最底部才能看到，详情查看[链接](https://www.algerfan.cn/articles/2019/12/15/1576381085019.html)

**Comment by zjhch123** [comment]
好的。我之后会参考一下掘金文章页的实现，做一下优化

**Comment by zjhch123** [comment]
已修复，参考了掘金文章目录以及社区文章目录的实现~

**Comment by AlgerFan** [comment]
> 已修复，参考了掘金文章目录以及社区文章目录的实现~

好的😄😄

**Comment by zjhch123** [comment]
> > 已修复，参考了掘金文章目录以及社区文章目录的实现~
> 
> 好的😄😄

注意必须基于solo 3.8版本使用哦！
