### ISSUE TITLE
静态统计修改

### ISSUE THREAD

**Issue by Vanessa219** [zjhch123/solo-skin-emiya#17]
文章列表浏览数、博客访问总数、文章页面浏览数等浏览数做了静态统计修改，请参考  [9IPHP](https://github.com/88250/solo/blob/master/src/main/resources/skins/9IPHP) 皮肤做如下类似的修改
https://github.com/88250/solo/blob/master/src/main/resources/skins/9IPHP/article-list.ftl#L61

**Comment by zjhch123** [comment]
好的，感谢提醒！

**Comment by AlgerFan** [comment]
似乎还更新了社区评论vcomment

**Comment by Vanessa219** [comment]
> 似乎还更新了社区评论vcomment

是的，可以参考 https://hacpai.com/article/1493814851007 进行修改
还有最近评论、访问最多文章、评论最多文章需要移除

**Comment by zjhch123** [comment]
> > 似乎还更新了社区评论vcomment
> 
> 是的，可以参考 https://hacpai.com/article/1493814851007 进行修改
> 还有最近评论、访问最多文章、评论最多文章需要移除

看来最近有大更新…

周末的时候统一修改吧~

**Comment by zjhch123** [comment]
修复完成！感觉侧边栏空空的  [Preview](https://blog.hduzplus.xyz)
