### ISSUE TITLE
代码块最大长度

### ISSUE THREAD

**Issue by Qiyue0726** [zjhch123/solo-skin-emiya#2]
一行代码很长也不会出现滚动条，导致页面很难看

![image](https://user-images.githubusercontent.com/33934935/62020774-df6c5200-b1f6-11e9-9cdf-eb743eaae0c7.png)

图中应该可以看到，浏览器出现滚动条，代码块那却没有

**Comment by zjhch123** [comment]
已更新，感谢反馈

**Comment by Qiyue0726** [comment]
> 已更新，感谢反馈

1000px还是好长啊，我是缩放125%

**Comment by zjhch123** [comment]
> > 已更新，感谢反馈
> 
> 1000px还是好长啊，我是缩放125%

能否麻烦提供一下最新的截图？

**Comment by Qiyue0726** [comment]
> > > 已更新，感谢反馈
> > 
> > 
> > 1000px还是好长啊，我是缩放125%
> 
> 能否麻烦提供一下最新的截图？

http://47.107.107.213/articles/2019/07/25/1564027279391.html
