### ISSUE TITLE
适配solo v3.9.0

### ISSUE THREAD

**Issue by zjhch123** [zjhch123/solo-skin-emiya#25]

**Comment by AlgerFan** [comment]
目录可以用了，是哪里出的问题呢？

**Comment by zjhch123** [comment]
> 目录可以用了，是哪里出的问题呢？

似乎是markdown渲染出的h标签的id有改变导致的

**Comment by AlgerFan** [comment]
> > 目录可以用了，是哪里出的问题呢？
> 
> 似乎是markdown渲染出的h标签的id有改变导致的

好的😁😁
