### ISSUE TITLE
关于目录的问题

### ISSUE THREAD

**Issue by NekoChips** [zjhch123/solo-skin-emiya#31]
问一下作者，有碰到过该皮肤在使用 lute 渲染后，文章目录消失的问题吗？

**Comment by zjhch123** [comment]
我暂时没有试过用`lute`渲染，迟点可以试试

你能提供一下文章目录消失时的截图，以及浏览器控制台里的输出吗？

**Comment by NekoChips** [comment]
不好意思，这两天比较忙，没有回复。截图如下：
![error_lute](https://user-images.githubusercontent.com/48819393/79035321-ece43380-7bef-11ea-977a-391722a29127.png)
![image](https://user-images.githubusercontent.com/48819393/79035332-10a77980-7bf0-11ea-81f5-c8d7f0b8ac7a.png)
控制台输出是正常的，就是在使用了 `lute` 之后，目录的 `div` 标签里的内容就没了。使用 `solo` 内置的皮肤是没有问题的。
`solo` 的版本为 4.0.0，不知道是否有这方面的影响。
ps: 图片可能加载出来是破图....

**Comment by zjhch123** [comment]
好的，我之后会修复~

近期我也会对皮肤进行升级以适配solo 4.0

**Comment by zjhch123** [comment]
已更新~可以检查一下是否已经修复
