### ISSUE TITLE
主题建议

### ISSUE THREAD

**Issue by chinagoldline** [zjhch123/solo-skin-emiya#33]
可以考虑将背景设置成变量，这样方便小白替换，哈哈。
刚换了张背景，[预览地址](https://www.mycitymemory.com/)

**Comment by zjhch123** [comment]
感谢建议，我会在下个版本进行优化

**Comment by zjhch123** [comment]
目前解析自定义模板变量的逻辑还有一些问题，已经给D发了issue，咱们先等等他的回复吧

[https://github.com/88250/solo/issues/123](https://github.com/88250/solo/issues/123)

**Comment by 88250** [comment]
感谢反馈和帮助排查，Solo master 上已经做出修复，最新的 Docker 镜像也已发布，可进行测试。

如果使用 zip 发布包的话请等 v4.1.0 发布，谢谢。

**Comment by zjhch123** [comment]
已更新~欢迎试用
