### ISSUE TITLE
适配一下Solo4.3.0版本

### ISSUE THREAD

**Issue by chinagoldline** [zjhch123/solo-skin-emiya#35]
比较喜欢这个主题，适配一下最新版吧，他好像评论要移除了。

**Comment by zjhch123** [comment]
好的，近期会进行适配

**Comment by AlgerFan** [comment]
大佬有空适配一下新版本吧，4.1.0版本后台发布文章不能用了

**Comment by zjhch123** [comment]
下周一定！

**Comment by Wh1teZe** [comment]
一人血书

**Comment by zjhch123** [comment]
已更新！欢迎尝鲜，捉虫 ;) [1.8.0](https://github.com/zjhch123/solo-skin-emiya/releases/tag/1.8.0)
